#ifndef __CERTS_H__
#define __CERTS_H__

const char ca_cert[] =
"-----BEGIN CERTIFICATE-----\r\n"
"MIIBozCCAUegAwIBAgIBATAMBggqhkjOPQQDAgUAMDAxCzAJBgNVBAMTAkNBMREw\r\n"
"DwYDVQQKEwhzZWN1cml0eTEOMAwGA1UEBhMFY2hpbmEwHhcNMTgwMTAxMDAwMDAw\r\n"
"WhcNMjIwMTAxMDAwMDAwWjAwMQswCQYDVQQDEwJDQTERMA8GA1UEChMIc2VjdXJp\r\n"
"dHkxDjAMBgNVBAYTBWNoaW5hMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE81rj\r\n"
"va1bE5pxBCgXppUHJNFc2K+lW7BzATgJMQ35Xn+jfWmYjeKL/TVCsZ/BMq8cKet/\r\n"
"xNrYI3Kjt1/pUOad76NQME4wDAYDVR0TBAUwAwEB/zAdBgNVHQ4EFgQUe18dVKQx\r\n"
"VPnwYtFmGfezOWZpmh4wHwYDVR0jBBgwFoAUe18dVKQxVPnwYtFmGfezOWZpmh4w\r\n"
"DAYIKoZIzj0EAwIFAANIADBFAiB94exApxOjGlXcv3c43Jzy1bHagUyT6DLvvGBm\r\n"
"rH+9xAIhANLtH5XjLJemGYJyhhg/Zo9HHRJxD2CYPFmK09JoR/Ph\r\n"
"-----END CERTIFICATE-----\r\n";

const char bob_cert[] =
"-----BEGIN CERTIFICATE-----\r\n"
"MIIBojCCAUWgAwIBAgIBATAMBggqhkjOPQQDAgUAMDAxCzAJBgNVBAMTAkNBMREw\r\n"
"DwYDVQQKEwhzZWN1cml0eTEOMAwGA1UEBhMFY2hpbmEwHhcNMTgwMTAxMDAwMDAw\r\n"
"WhcNMjIwMTAxMDAwMDAwWjAxMQwwCgYDVQQDEwNCb2IxETAPBgNVBAoTCHNlY3Vy\r\n"
"aXR5MQ4wDAYDVQQGEwVjaGluYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHnD\r\n"
"gZUEliDO7Rh9i9ehyr0UYxv0VQXt9F2kMh/c87FSztHeAy/GRBHyIhhMzZ25c+1j\r\n"
"pQSiRADIYC+hSQnCSvOjTTBLMAkGA1UdEwQCMAAwHQYDVR0OBBYEFLfb53i60Leg\r\n"
"/kgAYG9pf57UA60fMB8GA1UdIwQYMBaAFHtfHVSkMVT58GLRZhn3szlmaZoeMAwG\r\n"
"CCqGSM49BAMCBQADSQAwRgIhAMkQ0gvFdziJsAaKT/L33m8cdrXhhEe3tNCPlgS2\r\n"
"N3HtAiEAxNfZa5sWfe9bdf37PgkhHAC3oWnriSpSFqzrQ3Yhc0g=\r\n"
"-----END CERTIFICATE-----\r\n";

#endif